name: CI /CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black mypy structlog
      - name: Checking by flake8
        run: python -m flake8 --max-line-length=120
      - name: Checking by isort
        run: isort . --profile black
      - name: Checking by mypy
        run: mypy --exclude tests .
      - name: Checking by black
        run: black --check .
